version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:9019"
    volumes:
      - ./:/usr/src/backend
    env_file:
      - .env
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge